/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface BridgeInterface extends ethers.utils.Interface {
  functions: {
    "WETH()": FunctionFragment;
    "bridgeContracts(uint16)": FunctionFragment;
    "chainId()": FunctionFragment;
    "governanceActionIsConsumed(bytes32)": FunctionFragment;
    "governanceChainId()": FunctionFragment;
    "governanceContract()": FunctionFragment;
    "isInitialized(address)": FunctionFragment;
    "isTransferCompleted(bytes32)": FunctionFragment;
    "isWrappedAsset(address)": FunctionFragment;
    "outstandingBridged(address)": FunctionFragment;
    "parseRegisterChain(bytes)": FunctionFragment;
    "parseUpgrade(bytes)": FunctionFragment;
    "registerChain(bytes)": FunctionFragment;
    "tokenImplementation()": FunctionFragment;
    "upgrade(bytes)": FunctionFragment;
    "wormhole()": FunctionFragment;
    "wrappedAsset(uint16,bytes32)": FunctionFragment;
    "attestToken(address,uint32)": FunctionFragment;
    "wrapAndTransferETH(uint16,bytes32,uint256,uint32)": FunctionFragment;
    "transferTokens(address,uint256,uint16,bytes32,uint256,uint32)": FunctionFragment;
    "updateWrapped(bytes)": FunctionFragment;
    "createWrapped(bytes)": FunctionFragment;
    "completeTransfer(bytes)": FunctionFragment;
    "completeTransferAndUnwrapETH(bytes)": FunctionFragment;
    "encodeAssetMeta(tuple)": FunctionFragment;
    "encodeTransfer(tuple)": FunctionFragment;
    "parseAssetMeta(bytes)": FunctionFragment;
    "parseTransfer(bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "bridgeContracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "governanceActionIsConsumed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransferCompleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWrappedAsset",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "outstandingBridged",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "parseRegisterChain",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "parseUpgrade",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerChain",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "wormhole", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wrappedAsset",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapAndTransferETH",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokens",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWrapped",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createWrapped",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTransferAndUnwrapETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeAssetMeta",
    values: [
      {
        payloadID: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        decimals: BigNumberish;
        symbol: BytesLike;
        name: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeTransfer",
    values: [
      {
        payloadID: BigNumberish;
        amount: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        to: BytesLike;
        toChain: BigNumberish;
        fee: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "parseAssetMeta",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "parseTransfer",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceActionIsConsumed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTransferCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWrappedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outstandingBridged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseRegisterChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wormhole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrappedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrapAndTransferETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWrapped",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeTransferAndUnwrapETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeAssetMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseAssetMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseTransfer",
    data: BytesLike
  ): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "ContractUpgraded(address,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export class Bridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BridgeInterface;

  functions: {
    WETH(overrides?: CallOverrides): Promise<[string]>;

    bridgeContracts(
      chainId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    chainId(overrides?: CallOverrides): Promise<[number]>;

    governanceActionIsConsumed(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    governanceChainId(overrides?: CallOverrides): Promise<[number]>;

    governanceContract(overrides?: CallOverrides): Promise<[string]>;

    isInitialized(impl: string, overrides?: CallOverrides): Promise<[boolean]>;

    isTransferCompleted(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isWrappedAsset(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    outstandingBridged(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    parseRegisterChain(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, number, number, string] & {
          module: string;
          action: number;
          chainId: number;
          emitterChainID: number;
          emitterAddress: string;
        }
      ] & {
        chain: [string, number, number, number, string] & {
          module: string;
          action: number;
          chainId: number;
          emitterChainID: number;
          emitterAddress: string;
        };
      }
    >;

    parseUpgrade(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, number, number, string] & {
          module: string;
          action: number;
          chainId: number;
          newContract: string;
        }
      ] & {
        chain: [string, number, number, string] & {
          module: string;
          action: number;
          chainId: number;
          newContract: string;
        };
      }
    >;

    registerChain(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenImplementation(overrides?: CallOverrides): Promise<[string]>;

    upgrade(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wormhole(overrides?: CallOverrides): Promise<[string]>;

    wrappedAsset(
      tokenChainId: BigNumberish,
      tokenAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    attestToken(
      tokenAddress: string,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wrapAndTransferETH(
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferTokens(
      token: string,
      amount: BigNumberish,
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    completeTransfer(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    completeTransferAndUnwrapETH(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    encodeAssetMeta(
      meta: {
        payloadID: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        decimals: BigNumberish;
        symbol: BytesLike;
        name: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<[string] & { encoded: string }>;

    encodeTransfer(
      transfer: {
        payloadID: BigNumberish;
        amount: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        to: BytesLike;
        toChain: BigNumberish;
        fee: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<[string] & { encoded: string }>;

    parseAssetMeta(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, string, number, number, string, string] & {
          payloadID: number;
          tokenAddress: string;
          tokenChain: number;
          decimals: number;
          symbol: string;
          name: string;
        }
      ] & {
        meta: [number, string, number, number, string, string] & {
          payloadID: number;
          tokenAddress: string;
          tokenChain: number;
          decimals: number;
          symbol: string;
          name: string;
        };
      }
    >;

    parseTransfer(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, BigNumber, string, number, string, number, BigNumber] & {
          payloadID: number;
          amount: BigNumber;
          tokenAddress: string;
          tokenChain: number;
          to: string;
          toChain: number;
          fee: BigNumber;
        }
      ] & {
        transfer: [
          number,
          BigNumber,
          string,
          number,
          string,
          number,
          BigNumber
        ] & {
          payloadID: number;
          amount: BigNumber;
          tokenAddress: string;
          tokenChain: number;
          to: string;
          toChain: number;
          fee: BigNumber;
        };
      }
    >;
  };

  WETH(overrides?: CallOverrides): Promise<string>;

  bridgeContracts(
    chainId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  chainId(overrides?: CallOverrides): Promise<number>;

  governanceActionIsConsumed(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  governanceChainId(overrides?: CallOverrides): Promise<number>;

  governanceContract(overrides?: CallOverrides): Promise<string>;

  isInitialized(impl: string, overrides?: CallOverrides): Promise<boolean>;

  isTransferCompleted(
    hash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isWrappedAsset(token: string, overrides?: CallOverrides): Promise<boolean>;

  outstandingBridged(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  parseRegisterChain(
    encoded: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, number, string] & {
      module: string;
      action: number;
      chainId: number;
      emitterChainID: number;
      emitterAddress: string;
    }
  >;

  parseUpgrade(
    encoded: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, number, number, string] & {
      module: string;
      action: number;
      chainId: number;
      newContract: string;
    }
  >;

  registerChain(
    encodedVM: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenImplementation(overrides?: CallOverrides): Promise<string>;

  upgrade(
    encodedVM: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wormhole(overrides?: CallOverrides): Promise<string>;

  wrappedAsset(
    tokenChainId: BigNumberish,
    tokenAddress: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  attestToken(
    tokenAddress: string,
    nonce: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wrapAndTransferETH(
    recipientChain: BigNumberish,
    recipient: BytesLike,
    arbiterFee: BigNumberish,
    nonce: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferTokens(
    token: string,
    amount: BigNumberish,
    recipientChain: BigNumberish,
    recipient: BytesLike,
    arbiterFee: BigNumberish,
    nonce: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateWrapped(
    encodedVm: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createWrapped(
    encodedVm: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  completeTransfer(
    encodedVm: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  completeTransferAndUnwrapETH(
    encodedVm: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  encodeAssetMeta(
    meta: {
      payloadID: BigNumberish;
      tokenAddress: BytesLike;
      tokenChain: BigNumberish;
      decimals: BigNumberish;
      symbol: BytesLike;
      name: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<string>;

  encodeTransfer(
    transfer: {
      payloadID: BigNumberish;
      amount: BigNumberish;
      tokenAddress: BytesLike;
      tokenChain: BigNumberish;
      to: BytesLike;
      toChain: BigNumberish;
      fee: BigNumberish;
    },
    overrides?: CallOverrides
  ): Promise<string>;

  parseAssetMeta(
    encoded: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [number, string, number, number, string, string] & {
      payloadID: number;
      tokenAddress: string;
      tokenChain: number;
      decimals: number;
      symbol: string;
      name: string;
    }
  >;

  parseTransfer(
    encoded: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, string, number, string, number, BigNumber] & {
      payloadID: number;
      amount: BigNumber;
      tokenAddress: string;
      tokenChain: number;
      to: string;
      toChain: number;
      fee: BigNumber;
    }
  >;

  callStatic: {
    WETH(overrides?: CallOverrides): Promise<string>;

    bridgeContracts(
      chainId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    chainId(overrides?: CallOverrides): Promise<number>;

    governanceActionIsConsumed(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    governanceChainId(overrides?: CallOverrides): Promise<number>;

    governanceContract(overrides?: CallOverrides): Promise<string>;

    isInitialized(impl: string, overrides?: CallOverrides): Promise<boolean>;

    isTransferCompleted(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isWrappedAsset(token: string, overrides?: CallOverrides): Promise<boolean>;

    outstandingBridged(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseRegisterChain(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, number, string] & {
        module: string;
        action: number;
        chainId: number;
        emitterChainID: number;
        emitterAddress: string;
      }
    >;

    parseUpgrade(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, number, number, string] & {
        module: string;
        action: number;
        chainId: number;
        newContract: string;
      }
    >;

    registerChain(
      encodedVM: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenImplementation(overrides?: CallOverrides): Promise<string>;

    upgrade(encodedVM: BytesLike, overrides?: CallOverrides): Promise<void>;

    wormhole(overrides?: CallOverrides): Promise<string>;

    wrappedAsset(
      tokenChainId: BigNumberish,
      tokenAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    attestToken(
      tokenAddress: string,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wrapAndTransferETH(
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferTokens(
      token: string,
      amount: BigNumberish,
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateWrapped(
      encodedVm: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    createWrapped(
      encodedVm: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    completeTransfer(
      encodedVm: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    completeTransferAndUnwrapETH(
      encodedVm: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    encodeAssetMeta(
      meta: {
        payloadID: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        decimals: BigNumberish;
        symbol: BytesLike;
        name: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    encodeTransfer(
      transfer: {
        payloadID: BigNumberish;
        amount: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        to: BytesLike;
        toChain: BigNumberish;
        fee: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    parseAssetMeta(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, string, number, number, string, string] & {
        payloadID: number;
        tokenAddress: string;
        tokenChain: number;
        decimals: number;
        symbol: string;
        name: string;
      }
    >;

    parseTransfer(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, string, number, string, number, BigNumber] & {
        payloadID: number;
        amount: BigNumber;
        tokenAddress: string;
        tokenChain: number;
        to: string;
        toChain: number;
        fee: BigNumber;
      }
    >;
  };

  filters: {
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    ContractUpgraded(
      oldContract?: string | null,
      newContract?: string | null
    ): TypedEventFilter<
      [string, string],
      { oldContract: string; newContract: string }
    >;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;
  };

  estimateGas: {
    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    bridgeContracts(
      chainId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    governanceActionIsConsumed(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    governanceChainId(overrides?: CallOverrides): Promise<BigNumber>;

    governanceContract(overrides?: CallOverrides): Promise<BigNumber>;

    isInitialized(impl: string, overrides?: CallOverrides): Promise<BigNumber>;

    isTransferCompleted(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isWrappedAsset(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    outstandingBridged(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseRegisterChain(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseUpgrade(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerChain(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    upgrade(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wormhole(overrides?: CallOverrides): Promise<BigNumber>;

    wrappedAsset(
      tokenChainId: BigNumberish,
      tokenAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    attestToken(
      tokenAddress: string,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wrapAndTransferETH(
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferTokens(
      token: string,
      amount: BigNumberish,
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    completeTransfer(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    completeTransferAndUnwrapETH(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    encodeAssetMeta(
      meta: {
        payloadID: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        decimals: BigNumberish;
        symbol: BytesLike;
        name: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeTransfer(
      transfer: {
        payloadID: BigNumberish;
        amount: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        to: BytesLike;
        toChain: BigNumberish;
        fee: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseAssetMeta(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseTransfer(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridgeContracts(
      chainId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceActionIsConsumed(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    governanceChainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInitialized(
      impl: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTransferCompleted(
      hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWrappedAsset(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    outstandingBridged(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseRegisterChain(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseUpgrade(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerChain(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgrade(
      encodedVM: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wormhole(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wrappedAsset(
      tokenChainId: BigNumberish,
      tokenAddress: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    attestToken(
      tokenAddress: string,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wrapAndTransferETH(
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferTokens(
      token: string,
      amount: BigNumberish,
      recipientChain: BigNumberish,
      recipient: BytesLike,
      arbiterFee: BigNumberish,
      nonce: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createWrapped(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    completeTransfer(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    completeTransferAndUnwrapETH(
      encodedVm: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    encodeAssetMeta(
      meta: {
        payloadID: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        decimals: BigNumberish;
        symbol: BytesLike;
        name: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeTransfer(
      transfer: {
        payloadID: BigNumberish;
        amount: BigNumberish;
        tokenAddress: BytesLike;
        tokenChain: BigNumberish;
        to: BytesLike;
        toChain: BigNumberish;
        fee: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseAssetMeta(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseTransfer(
      encoded: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
