/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WormholeAbi } from "./WormholeAbi";

export { WormholeAbi__factory } from "./factories/WormholeAbi__factory";
